[package]
name = "keypropdecode"
version = "0.0.0"
edition = "2021"
authors = ["kinire98"]
description = "Reserved"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
